adding '-e' option

diff --git a/cbcenter b/cbcenter
--- a/cbcenter
+++ b/cbcenter
@@ -489,12 +489,12 @@ Re-run '$mybasename fetch-more username'." 1>&2
             ;;
         "$INVALID_VALUE")
             shift
-            echo "invalid $*"
+            echo -e "invalid $*"
             exit $INVALID_VALUE
             ;;
         *)
             shift
-            echo "UNKNOWN_ERROR due to $*" 1>&2
+            echo -e "UNKNOWN_ERROR due to $*" 1>&2
             exit $UNKNOWN_ERROR
             ;;
     esac
