redirect stdout to stderr in 'rm' error

diff --git a/cbcenter b/cbcenter
--- a/cbcenter
+++ b/cbcenter
@@ -923,7 +923,7 @@ clear_favorites_dir () {
     if rm -f "${FAVORITES_PDIR:?}"/*; then
         echo -n "  "; echo "Old content of directory FAVORITES deleted!"
     else
-        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing FAVORITES!"
+        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing FAVORITES!" 1>&2
     fi
 }
 
@@ -932,7 +932,7 @@ clear_captures_dir () {
     if rm -f "${CAPTURES_PDIR:?}"/*; then
         echo -n "  "; echo "Old content of directory CAPTURES deleted!"
     else
-        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing CAPTURES!"
+        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing CAPTURES!" 1>&2
     fi
 }
 
@@ -941,7 +941,7 @@ clear_streams_dir () {
     if rm -f "${STREAMS_PDIR:?}"/*; then
         echo -n "  "; echo "Old content of directory STREAMS deleted!"
     else
-        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing STREAMS!"
+        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing STREAMS!" 1>&2
     fi
 }
 
@@ -950,7 +950,7 @@ clear_others_dir () {
     if rm -f "${OTHERS_PDIR:?}"/*; then
         echo -n "  "; echo "Old content of directory OTHERS deleted!"
     else
-        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing OTHERS!"
+        echo -n "  "; echo -e "An ${RED_FG}error${CLEAR_FG} occurred while clearing OTHERS!" 1>&2
     fi
 }
 
@@ -1692,7 +1692,7 @@ clear_more_dir () {
     if rm -f "${MORE_PDIR:?}"/*; then
         echo -n "  "; echo "Old content of directory MORE deleted!"
     else
-        echo -n "  "; echo "An ${RED_FG}error${CLEAR_FG} occurred while clearing MORE!"
+        echo -n "  "; echo "An ${RED_FG}error${CLEAR_FG} occurred while clearing MORE!" 1>&2
     fi
 }
 
