adding new 'fetch-others' implementation

diff --git a/cbcenter b/cbcenter
--- a/cbcenter
+++ b/cbcenter
@@ -82,6 +82,10 @@ PROG_REGEX="BANDWIDTH=[0-9]+,NAME=\"FPS:[0-9]+\.[0-9]+\",CODECS=\"[a-z0-9.,]*\",
 ROOM_REGEX="^${USER_REGEX}$"
 GENDER_REGEX="${FEMALE_ROOM}|${MALE_ROOM}|${COUPLE_ROOM}|${TRANS_ROOM}"
 ROOM_RANGE_REGEX="^(($GENDER_REGEX):[0-9]{0,2}:[0-9]{1,2})$"
+FETCH_DIGITS_REGEX="[0-9]{1,2}"
+AGE_REGEX="[0-9]{2}"
+MIN_AGE=18
+MAX_AGE=99
 
 # ----------- TOOLS ------------
 JQ_ONLINE="online"
@@ -332,8 +336,8 @@ TIP: If [username] is not provided, you will be asked to choose an option\n\
   are not valid: '# Setting to 0 because...' or ' VIEWER=\"imv -fd\" '\n\
                   ^ comment                      ^                ^\n\
                                                  ^ unnecessary spaces\nFilters:\n\n\
-  -g gender --> gender: Gender of room users.\n\
-      'f' (female) or 'm' (male) or 'c' (couple) or 't' (trans)\n\
+  -g gender[,gender2[...[,genderN]]] --> gender(s): Gender of room users.\n\
+      'f' (female), 'm' (male), 'c' (couple), 't' (trans)\n\
       example: -g c\n\
       If none is provided, fetch mixed rooms.\n\
   -o offset --> offset: Beginning room.\n\
@@ -342,14 +346,14 @@ TIP: If [username] is not provided, you will be asked to choose an option\n\
   -l limit --> limit: Number of rooms.\n\
       Two digits (max) integer from 1 (or 01) to 99.\n\
       If none is provided, the value of FETCH_STEPS is taken.\n\
-  -a from:to --> age range\n\
-      examples: -a 20:25 (from 20 to 25)\n\
-                -a :30   (from 18 to 30)\n\
-                -a 22:   (from 22)\n\
-  -r region[,region2[...]] --> region(s)\n\
+  -f from --> from age\n\
+      examples: -f 20\n\
+  -t to --> to age\n\
+      example: -t 30\n\
+  -r region[,region2[...[,regionN]]] --> region(s)\n\
       AS (Asia), ER (Europe/Russia), NA (North America), SA (South America), O (Other).\n\
       example: -r NA,SA,O\n\
-  -h hashtag[,hashtag2[...]] --> hashtag(s)\n\
+  -h hashtag[,hashtag2[...[,hashtagN]]] --> hashtag(s)\n\
       example: -h hotkeys,bigbus,threadpool\n\nDirectories and files:\n\n\
   PROJECT DIR:   $MYPATH/\n\
   CONFIG DIR:    $MYCONFIG_PDIR/\n\
@@ -405,6 +409,7 @@ TIP: If [username] is not provided, you will be asked to choose an option\n\
 # Send error message and exit program
 # '$1' error code
 send_exit_error () {
+    unset IFS
     echo -n "$mybasename: error: " 1>&2
     case "$1" in
         "$INVALID_USERNAME")
@@ -513,7 +518,8 @@ Re-run '$mybasename fetch-more username'." 1>&2
             exit $CONNECTION_ERROR
             ;;
         *)
-            echo "UNKNOWN_ERROR" 1>&2
+            shift
+            echo "UNKNOWN_ERROR due to $*" 1>&2
             exit $UNKNOWN_ERROR
             ;;
     esac
@@ -1269,12 +1275,12 @@ open_others_dir () {
 }
 
 # Save rooms list from given range on '$4' file.
-# '$1' gender
-# '$2' offset
-# '$3' limit
+# '$1' offset
+# '$2' limit
+# '$3' extra parameters (&key1=value1&key2=value2...&keyN=valueN)
 # '$4' output
 fetch_roomlist_file () {
-    curl -sL --compressed -H "$XRW_HEADER" "$ROOMLIST_PURL/?genders=$1&offset=$2&limit=$3&enable_recommendations=false" -o "$4"
+    curl -sL --compressed -H "$XRW_HEADER" "$ROOMLIST_PURL/?offset=$1&limit=$2&enable_recommendations=false$3" -o "$4"
 }
 
 show_fetch_message () {
@@ -1361,27 +1367,124 @@ fetch_rooms_using () {
     done
 }
 
-# Get and show rooms from given range
-# '$1' range
-fetch_other_rooms () {
-    valid_room_range "$1" || send_exit_error $INVALID_ROOM_RANGE
-    local gender
-    # Extract gender
-    gender="${1%%:*}"
-    local offset
-    # Extract offset
-    offset="${1#*:}"
-    offset="${offset%:*}"
-    [[ -z $offset ]] && offset=0
-    offset="$(remove_leading_zeros "$offset")"
-    local limit
-    # Extract limit
-    limit="${1##*:}"
-    limit="$(remove_leading_zeros "$limit")"
-    [[ $limit -eq 0 ]] && send_exit_error $INVALID_ROOM_RANGE
+valid_region () {
+    [[ "$1" == "AS" ]] ||
+        [[ "$1" == "ER" ]] ||
+        [[ "$1" == "NA" ]] ||
+        [[ "$1" == "SA" ]] ||
+        [[ "$1" == "O" ]]
+}
 
-    echo "Fetching $gender rooms from $offset to $((offset+limit-1)) ..."
-    fetch_roomlist_file "$gender" "$offset" "$limit" "$OTHERS_FILE" || send_exit_error $ROOM_LIST_ERROR
+# Only keep one copy of the consecutive pattern in '$1'
+# example: $1='a,,bb,ccc,,,,dddd,,' and $2=','
+#          output --> 'a,bb,ccc,dddd,'
+# '$1' string
+# '$2' pattern
+unify_repeated () {
+    shopt -s extglob
+    echo "${1//+(,)/,}"
+}
+
+# Get and show rooms from given range
+# '$1' offset
+# '$2' limit
+# '$3' gender(s)
+# '$4' from age
+# '$5' to age
+# '$6' region(s)
+# '$7' hashtag(s)
+fetch_other_rooms () {
+    local offset="$1"
+    if [[ -n "$offset" ]]; then
+        [[ "$offset" =~ ^($FETCH_DIGITS_REGEX)$ ]] || send_exit_error $UNKNOWN_ERROR $1
+        offset="$(remove_leading_zeros "$offset")"
+    else
+        offset=0
+    fi
+    local limit="$2"
+    if [[ -n "$limit" ]]; then
+        [[ "$limit" =~ ^($FETCH_DIGITS_REGEX)$ ]] || send_exit_error $UNKNOWN_ERROR $2
+        limit="$(remove_leading_zeros "$limit")"
+    else
+        limit="$FETCH_STEPS"
+    fi
+    local xtras
+    local genders="$3"
+    if [[ -n "$genders" ]]; then
+        genders="$(unify_repeated "$genders" ,)"
+        genders="${genders#,}"
+        genders="${genders%,}"
+        IFS=","
+        # check genders
+        for g in $genders; do
+            [[ "$g" =~ ^($GENDER_REGEX)$ ]] ||
+                send_exit_error $UNKNOWN_ERROR $g
+        done
+        unset IFS
+        xtras+="&genders=$genders"
+    fi
+    local from_age="$4"
+    if [[ -n "$from_age" ]]; then
+        [[ "$from_age" =~ ^($AGE_REGEX)$ ]] || send_exit_error $UNKNOWN_ERROR $4
+        from_age="$(remove_leading_zeros "$from_age")"
+        [[ $from_age -ge $MIN_AGE && $from_age -le $MAX_AGE ]] || send_exit_error $UNKNOWN_ERROR "from < 18"
+    fi
+    local to_age="$5"
+    if [[ -n "$to_age" ]]; then
+        [[ "$to_age" =~ ^($AGE_REGEX)$ ]] || send_exit_error $UNKNOWN_ERROR $5
+        to_age="$(remove_leading_zeros "$to_age")"
+        [[ $to_age -ge $MIN_AGE && $to_age -le $MAX_AGE ]] || send_exit_error $UNKNOWN_ERROR "to < 18"
+    fi
+    if [[ -z "$from_age" && -n "$to_age" ]]; then
+        from_age="$MIN_AGE"
+    elif [[ -z "$to_age" && -n "$from_age" ]]; then
+        to_age="$MAX_AGE"
+    fi
+    if [[ -n "$from_age" && -n "$to_age" ]]; then
+        [[ $from_age -gt $to_age ]] &&
+            send_exit_error $UNKNOWN_ERROR "from ($from_age) > to ($to_age)"
+        xtras+="&ages=$from_age-$to_age"
+        xtras+="&from_age=$from_age"
+        # xtras+="&to_age=$to_age"
+        xtras+="&to_age=$((to_age+1))"
+    fi
+    local regions="$6"
+    if [[ -n "$regions" ]]; then
+        regions="$(unify_repeated "$regions" ,)"
+        regions="${regions#,}"
+        regions="${regions%,}"
+        IFS=","
+        # check regions
+        for r in $regions; do
+            valid_region "$r" || send_exit_error $UNKNOWN_ERROR "$r"
+        done
+        unset IFS
+        xtras+="&regions=$regions"
+    fi
+    local hashtags="$7"
+    if [[ -n "$hashtags" ]]; then
+        hashtags="$(unify_repeated "$hashtags" ,)"
+        hashtags="${hashtags#,}"
+        hashtags="${hashtags%,}"
+        IFS=","
+        # check hashtags
+        for h in $hashtags; do
+            valid_username "$h" || send_exit_error $UNKNOWN_ERROR "$h"
+        done
+        unset IFS
+        xtras+="&hashtags=$hashtags"
+    fi
+    echo "offset:  $offset"
+    echo "limit:   $limit"
+    echo "genders: $genders"
+    echo "from:    $from_age"
+    echo "to:      $to_age"
+    echo "region:  $regions"
+    echo "hashtag: $hashtags"
+    echo "$xtras"
+
+    echo "Fetching ${genders:-mixed} rooms ${offset:+from $offset to $((offset+limit-1))} ..."
+    fetch_roomlist_file "$offset" "$limit" "$xtras" "$OTHERS_FILE" || send_exit_error $ROOM_LIST_ERROR
     show_fetch_message
     echo -e "${GREEN_FG}INFO:${CLEAR_FG} Sometimes promoted rooms appear. For this reason, it is possible\n\
 that more than $limit rooms will be obtained."
@@ -1827,9 +1930,14 @@ case "$command" in
                     gparam="$(trim_string "$2")"
                     shift 2
                     ;;
-                -a)
+                -f)
                     [[ -z "$2" ]] && send_exit_error $UNKNOWN_ERROR
-                    aparam="$(trim_string "$2")"
+                    fparam="$(trim_string "$2")"
+                    shift 2
+                    ;;
+                -t)
+                    [[ -z "$2" ]] && send_exit_error $UNKNOWN_ERROR
+                    tparam="$(trim_string "$2")"
                     shift 2
                     ;;
                 -r)
@@ -1847,14 +1955,8 @@ case "$command" in
                     ;;
             esac
         done
-        echo "oparam: $oparam"
-        echo "lparam: $lparam"
-        echo "gparam: $gparam"
-        echo "aparam: $aparam"
-        echo "rparam: $rparam"
-        echo "hparam: $hparam"
-        #fetch_other_rooms "$param" "$aparam" "$rparam" "$hparam"
-        #play_other_choice hide_list
+        fetch_other_rooms "$oparam" "$lparam" "$gparam" "$fparam" "$tparam" "$rparam" "$hparam"
+        play_other_choice hide_list
         ;;
     vo|view-others)
         open_others_dir
