adding gender choice on 'fetch-random' command

diff --git a/cbcenter b/cbcenter
--- a/cbcenter
+++ b/cbcenter
@@ -735,10 +735,15 @@ open_random_file () {
     $VIEWER ${RANDOM_FILE_T:?}*
 }
 
-# Fetch random preview using a custom range (*:*:1)
+# Fetch random preview using a custom range ('$1':RANDOM:1 or RANDOM:RANDOM:1 if '$1' is empty)
+# '$1' gender
 fetch_random_room () {
-    local gender
-    case $((RANDOM%4)) in
+    local gender="$1"
+    if [[ -n "$gender" ]] && ! [[ "$gender" =~ ^$FEMALE_ROOM|$MALE_ROOM|$COUPLE_ROOM|$TRANS_ROOM$ ]]; then
+        echo "Invalid gender"
+        exit $UNKNOWN_ERROR
+    fi
+    [[ -z "$gender" ]] && case $((RANDOM%4)) in
         0) gender=f
             ;;
         1) gender=m
@@ -834,7 +839,7 @@ case "$1" in
         open_rooms_dir
         ;;
     fetch-random)
-        fetch_random_room
+        fetch_random_room "$2"
         ;;
     view-random)
         open_random_file
