splitting 'assert_active_room' implementation

diff --git a/cbcenter b/cbcenter
--- a/cbcenter
+++ b/cbcenter
@@ -421,16 +421,34 @@ is_online () {
     curl_search "$1" | jq -Mc ".${JQ_ONLINE}" | grep -q "\"$1\""
 }
 
+fetch_room_status () {
+    fetch_bio "$1"
+    local frs_out
+    if ! frs_out="$(jq -Mr ".${JQ_BIO_RSTATUS}" "$BIOCONTEXT_FILE" 2>/dev/null)";
+    then
+        [[ "$2" == "hide" ]] || echo "not found"
+        return $ROOM_NOT_FOUND
+    fi
+    if [[ "$frs_out" == "null" ]]; then
+        [[ "$2" == "hide" ]] || echo "banned"
+        return $BANNED_ROOM
+    fi
+    [[ "$2" == "hide" ]] || echo "$frs_out"
+    return $OK_CODE
+}
+
 # Store room_status field on '$2' from biocontext file (JSON)
 # Also send exit error if the room: doesnt exist or is banned.
 # '$1' room
 # '$2' store room_status
 assert_active_room () {
-    [[ -n "$2" ]] && declare -n rs_out="$2"
-    fetch_bio "$1"
-    rs_out="$(jq -Mr ".${JQ_BIO_RSTATUS}" "$BIOCONTEXT_FILE" 2>/dev/null)" ||
-        send_exit_error $ROOM_NOT_FOUND
-    [[ "$rs_out" == "null" ]] && send_exit_error $BANNED_ROOM
+    if [[ -n "$2" ]]; then
+        declare -n rs_out="$2"
+        rs_out="$(fetch_room_status "$1")" || send_exit_error $?
+        [[ -z "$rs_out" ]] && send_exit_error $UNKNOWN_ERROR
+        return $OK_CODE
+    fi
+    fetch_room_status "$1" hide || send_exit_error $?
 }
 
 # return 0 if valid, else 1
@@ -693,21 +711,6 @@ more_room_choice () {
     [[ -z $mrc_out ]] && send_exit_error $UNKNOWN_ERROR
 }
 
-message_active_room () {
-    [[ -n "$2" ]] && declare -n rs_out="$2"
-    fetch_bio "$1"
-    if ! rs_out="$(jq -Mr ".${JQ_BIO_RSTATUS}" "$BIOCONTEXT_FILE" 2>/dev/null)";
-    then
-        echo "'$1' not found."
-        return $ROOM_NOT_FOUND
-    fi
-    if [[ "$rs_out" == "null" ]]; then
-        echo "'$1' is banned from the site."
-        return $BANNED_ROOM
-    fi
-    return $OK_CODE
-}
-
 # Add new room to favorites
 # '$1' room
 add_multi_room () {
@@ -721,7 +724,10 @@ add_multi_room () {
             continue
         fi
         local ar_status
-        message_active_room "$a" ar_status || continue
+        if ! ar_status="$(fetch_room_status "$a")"; then
+            echo "'$a' --> $ar_status"
+            continue
+        fi
         echo "$a" >> "$FAVORITES_FILE" && echo "'$a' added! The room is $ar_status"
     done
 }
